default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "db/development.sqlite3"

test:
  <<: *default
  database: "db/test.sqlite3"

production:
  <<: *default
  database: d74ft47a7s8k34
  username: vwkmlzwlzpdjpg
  host: ec2-18-208-55-135.compute-1.amazonaws.com
  password: 0cf36923eb36eedea39059c5dfd0b602d80cbaeb649b54bf5f50d41a5ac478d0